Repository SPR-NBcamp-Number14/Android_MyMedia, pull requests merged in 2023-09, with the labels that each got.

#6 [MERGE] : ✅ 검색 UI 구현
  app/src/main/java/com/example/android_mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/ShortAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/data/ResponseVideo.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepository.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/home/repository/Repository.kt
  app/src/main/java/com/example/android_mymedia/home/repository/RepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/search/SearchAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/android_mymedia/unit/Unit.kt
  app/src/main/res/drawable/border_search_bar.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_close.xml
  app/src/main/res/drawable/ic_search_frag_img.xml
  app/src/main/res/drawable/img_dummy_gundam.png
  app/src/main/res/layout/home_category_list.xml
  app/src/main/res/layout/home_short_item.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/search_item_category.xml
  app/src/main/res/layout/search_item_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: merge

#7 [MERGE] : ✅ 레트로핏 연결완료
  app/src/main/java/com/example/android_mymedia/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/main/MainActivity.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/res/layout/home_category_item.xml
Labels: feature

#9 [MERGE] : ✅ Detail Fragment 중간 merge
  app/src/main/java/com/example/android_mymedia/detail/DetailFragment.kt
  app/src/main/java/com/example/android_mymedia/main/ViewPagerAdapter.kt
  app/src/main/res/drawable/clicked_confirm_like_button.xml
  app/src/main/res/drawable/clicked_not_pressed_like_button.xml
  app/src/main/res/drawable/confirm_like_button.xml
  app/src/main/res/drawable/confirm_share_button.xml
  app/src/main/res/drawable/ic_back_button.png
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/ic_heart_drawable.xml
  app/src/main/res/drawable/ic_heart_filled.png
  app/src/main/res/drawable/ic_heart_filled_drawable.xml
  app/src/main/res/drawable/ic_share.png
  app/src/main/res/drawable/ic_share_drawable.xml
  app/src/main/res/drawable/ic_video.png
  app/src/main/res/drawable/not_pressed_like_button.xml
  app/src/main/res/drawable/not_pressed_share_button.xml
  app/src/main/res/drawable/pressed_like_button.xml
  app/src/main/res/drawable/pressed_share_button.xml
  app/src/main/res/layout/detail_fragment.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#10 [MERGE] : ✅: home화면 기능 구성
  app/src/main/java/com/example/android_mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/ShortAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/data/ResponseVideo.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepository.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/search/SearchAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/android_mymedia/search/SearchViewModel.kt
  app/src/main/java/com/example/android_mymedia/searchdata/ResponseSearch.kt
  app/src/main/java/com/example/android_mymedia/searchdata/SearchListModel.kt
  app/src/main/java/com/example/android_mymedia/searchrepository/SearchRepository.kt
  app/src/main/java/com/example/android_mymedia/searchrepository/SearchRepositoryImpl.kt
  app/src/main/res/layout/home_category_item.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_short_item.xml
  app/src/main/res/layout/home_video_item.xml
  app/src/main/res/layout/search_fragment.xml
Labels: feature, UI, merge

#12 [FEAT] : ⚙️ Adapter, Detail Activity 연동 및 데이터 출력
  app/build.gradle
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/detail/DetailFragment.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/main/ViewPagerAdapter.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/values/strings.xml
Labels: feature

#13 [MERGE] : ✅ 홈
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android_mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/data/ResponseVideo.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepository.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/unit/Unit.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/layout/home_video_item.xml
Labels: bug, feature, UI

#15 [MERGE] : ✅ 홈 #4
  app/src/main/java/com/example/android_mymedia/home/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/HomeViewModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/data/ResponseVideo.kt
Labels: bug, feature
