Repository SPR-NBcamp-Number14/Android_MyMedia, pull requests merged in 2023-10, with the labels that each got.

#18 [DESIGN] : 🎨: 마이 비디오 ui
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoAdapter.kt
  app/src/main/res/drawable/pro_default.png
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/layout/my_video_item_list.xml
  app/src/main/res/layout/search_item_list.xml
Labels: UI

#19 [MERGE] : ✅ 오류 수정
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/detail/DetailModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/BtnsAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/model/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/fragment/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoAdapter.kt
  app/src/main/res/drawable/btn_border_clicked.xml
  app/src/main/res/drawable/btn_top.xml
  app/src/main/res/layout/home_btn_item.xml
  app/src/main/res/layout/search_item_list.xml
Labels: bug, merge

#20 [MERGE] : ✅ 검색화면 & 파일 변경
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/search/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/android_mymedia/search/SearchViewModel.kt
  app/src/main/java/com/example/android_mymedia/search/searchdata/ResponseSearch.kt
  app/src/main/java/com/example/android_mymedia/search/searchdata/SearchListModel.kt
  app/src/main/java/com/example/android_mymedia/search/searchrepository/SearchRepository.kt
  app/src/main/java/com/example/android_mymedia/search/searchrepository/SearchRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/searchdata/SearchListModel.kt
  app/src/main/java/com/example/android_mymedia/searchrepository/SearchRepository.kt
  app/src/main/java/com/example/android_mymedia/searchrepository/SearchRepositoryImpl.kt
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/search_item_list.xml
Labels: bug

#22 [MERGE] : ✅ 룸 기능 추가 및 충돌 병합
  app/build.gradle
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/room/VideoDAO.kt
  app/src/main/java/com/example/android_mymedia/room/VideoDatabase.kt
  app/src/main/java/com/example/android_mymedia/room/VideoEntity.kt
  app/src/main/java/com/example/android_mymedia/unit/Unit.kt
  app/src/main/res/layout/detail_activity.xml
Labels: feature, merge

#23 [MERGE] : ✅ 병합 충돌 해결 및 my video 더미 데이터 삽입
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/detail/DetailModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/BtnsAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/api/ResponseCategory.kt
  app/src/main/java/com/example/android_mymedia/home/data/api/ResponseVideo.kt
  app/src/main/java/com/example/android_mymedia/home/data/model/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/home/fragment/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoViewModel.kt
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/unit/Unit.kt
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/layout/search_item_list.xml
Labels: bug, feature, UI, Refect, merge

#25 [MERGE] : ✅ myvideo-room연결
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/detail/DetailModel.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/BtnsAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/data/model/PlayListModel.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoFragment.kt
  app/src/main/java/com/example/android_mymedia/my_video/MyVideoViewModel.kt
  app/src/main/java/com/example/android_mymedia/my_video/repository/MyRepository.kt
  app/src/main/java/com/example/android_mymedia/my_video/repository/MyRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/room/VideoDAO.kt
  app/src/main/java/com/example/android_mymedia/room/VideoEntity.kt
  app/src/main/res/drawable/btn_top.xml
  app/src/main/res/layout/my_video_item_list.xml
Labels: feature, UI

#26 [MERGE] : ✅ 공유하기 기능 수정 및 썸네일 대신 유튜브 영상 재생 기능 추가
  app/build.gradle
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/res/layout/detail_activity.xml
Labels: bug, feature

#27 [MERGE] : ✅ 코드 리팩토링 및 myfragment추가
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/java/com/example/android_mymedia/home/adapter/VideoAdapter.kt
  app/src/main/java/com/example/android_mymedia/home/fragment/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/myfragment/GYFragment.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepository.kt
  app/src/main/java/com/example/android_mymedia/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/android_mymedia/home/viewmdoel/HomeClickEvent.kt
  app/src/main/java/com/example/android_mymedia/home/viewmdoel/HomeViewModel.kt
  app/src/main/java/com/example/android_mymedia/unit/SingleLiveEvent.kt
  app/src/main/res/layout/g_y_fragment.xml
  app/src/main/res/xml/g_y_fragment_scene.xml
Labels: feature, Refect, merge

#30 [FEAT] : ⚙️: 모션 레이아웃
  app/src/main/res/layout/my_video_fragment.xml
  app/src/main/res/xml/my_video_fragment_scene.xml
Labels: feature

#31 [MERGE] : ✅ home 모션 레이아웃 적용
  app/src/main/java/com/example/android_mymedia/home/fragment/HomeFragment.kt
  app/src/main/java/com/example/android_mymedia/home/myfragment/GYFragment.kt
  app/src/main/res/drawable/btn_background_circle.xml
  app/src/main/res/drawable/ic_arrow_bottom.xml
  app/src/main/res/drawable/ic_arrow_top.xml
  app/src/main/res/drawable/ic_cross.xml
  app/src/main/res/layout/g_y_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/xml/home_fragment_scene.xml
Labels: UI

#33 [MERGE] : ✅ 서치 프래그먼트 병합
  app/build.gradle
  app/src/main/java/com/example/android_mymedia/retrofit/RetrofitInterface.kt
  app/src/main/java/com/example/android_mymedia/search/CategoryAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/android_mymedia/search/SearchViewModel.kt
  app/src/main/java/com/example/android_mymedia/search/searchdata/SearchListModel.kt
  app/src/main/java/com/example/android_mymedia/search/searchrepository/SearchRepository.kt
  app/src/main/java/com/example/android_mymedia/search/searchrepository/SearchRepositoryImpl.kt
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/search_item_category.xml
  app/src/main/res/layout/search_item_list.xml
  app/src/main/res/xml/search_fragment_scene.xml
Labels: merge

#34 [MERGE] : ✅ 코드 리팩토링
  app/src/main/java/com/example/android_mymedia/search/SearchAdapter.kt
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
  app/src/main/java/com/example/android_mymedia/search/searchdata/SearchListModel.kt
Labels: feature, Refect

#35 [FEAT] : ⚙️ Detail Activity Motion Layout 기능 추가
  app/src/main/java/com/example/android_mymedia/detail/DetailActivity.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/xml/detail_activity_scene.xml
Labels: feature

#37 [REFACTOR] : ♻️: 위치 변경
  app/src/main/java/com/example/android_mymedia/search/SearchFragment.kt
Labels: Refect

#39 [MERGE] : 🔧 Navigation Bar 및 카테고리 버튼 UI 수정
  app/src/main/res/color/bottom_nav_item_color.xml
  app/src/main/res/drawable/btn_border.xml
  app/src/main/res/drawable/btn_border_clicked.xml
  app/src/main/res/layout/home_btn_item.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI
